version: "3"
services:
  redis:
    image: redis
    ports:
      - 6400:6379
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./database/sql:/sql
    ports:
      - 3400:3306
    

